sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t piquesel78/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true piquesel78/react-test npm test

after_success:
  - docker build -t piquesel78/multi-client ./client
  - docker build -t piquesel78/multi-nginx ./nginx
  - docker build -t piquesel78/multi-server ./server
  - docker build -t piquesel78/multi-worker ./worker
# Log into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push piquesel78/multi-client
  - docker push piquesel78/multi-nginx
  - docker push piquesel78/multi-server
  - docker push piquesel78/multi-worker
